export const FAILURE_TYPES = {
  CURSOR_EXECUTION_FAILED: "CURSOR_EXECUTION_FAILED",
  GIT_APPLY_FAILED: "GIT_APPLY_FAILED",
  GIT_CONFLICT: "GIT_CONFLICT",
  PR_CREATION_FAILED: "PR_CREATION_FAILED",
  AUTH_ERROR: "AUTH_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  UNKNOWN: "UNKNOWN",
} as const;

export type FailureType = (typeof FAILURE_TYPES)[keyof typeof FAILURE_TYPES];

