/** Integration Preview용 샘플 UI — 인라인 스타일로 기존 shell CSS 없이도 ‘실제 화면’ 톤 유지 */

export const PREVIEW_SAMPLE_WIRING_VERSION = "v2" as const;

export const PREVIEW_SAMPLE_FILE_LIST_JSX = `<div className="jy-preview-file-list" data-jy-preview-sample="${PREVIEW_SAMPLE_WIRING_VERSION}" style={{ display: "flex", flexDirection: "column", gap: 8 }}>{sampleMeetingFiles.map((file) => (<button key={file.id} type="button" style={{ textAlign: "left", padding: "10px 12px", border: "1px solid #e2e8f0", borderRadius: 8, background: "#fff", cursor: "default" }}><div style={{ fontWeight: 600, fontSize: 13 }}>{file.name}</div><div style={{ fontSize: 12, color: "#64748b", marginTop: 4 }}>{[file.duration, file.uploadedAt].filter(Boolean).join(" · ")}</div></button>))}</div>`;

export const PREVIEW_SAMPLE_PARTICIPANT_LIST_JSX = `<div className="jy-preview-participant-list" data-jy-preview-sample="${PREVIEW_SAMPLE_WIRING_VERSION}" style={{ display: "flex", flexDirection: "column", gap: 6 }}>{sampleParticipants.map((p) => { const label = String(p.name ?? p.displayName ?? "").trim() || "참여자"; const role = String(p.role ?? p.title ?? "").trim(); return (<div key={p.id} style={{ display: "flex", alignItems: "center", gap: 10, padding: "8px 10px", borderRadius: 8, background: "#f8fafc" }}><span style={{ width: 32, height: 32, borderRadius: "50%", background: "#2563eb", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 600 }}>{label.slice(0, 1)}</span><div><div style={{ fontWeight: 600, fontSize: 13 }}>{label}</div>{role ? <div style={{ fontSize: 12, color: "#64748b" }}>{role}</div> : null}</div></div>); })}</div>`;

export const PREVIEW_SAMPLE_TRANSCRIPT_JSX = `<div className="jy-preview-transcript" data-jy-preview-sample="${PREVIEW_SAMPLE_WIRING_VERSION}" style={{ display: "flex", flexDirection: "column", gap: 12, padding: "4px 0" }}>{sampleTranscriptSegments.map((seg) => { const ts = String(seg.timestamp ?? seg.time ?? "").trim(); const speaker = String(seg.speakerName ?? seg.speaker ?? "화자").trim(); return (<div key={seg.id} style={{ display: "flex", gap: 10, alignItems: "flex-start" }}><span style={{ fontSize: 11, color: "#94a3b8", minWidth: 44, fontVariantNumeric: "tabular-nums" }}>{ts || "00:00"}</span><div style={{ flex: 1, background: "#f1f5f9", borderRadius: 10, padding: "10px 12px" }}><div style={{ fontWeight: 600, fontSize: 12, marginBottom: 4, color: "#334155" }}>{speaker}</div><div style={{ fontSize: 13, lineHeight: 1.5, color: "#1e293b" }}>{seg.text}</div></div></div>); })}</div>`;

export const PREVIEW_SAMPLE_SUMMARY_JSX = `<div className="jy-preview-summary" data-jy-preview-sample="${PREVIEW_SAMPLE_WIRING_VERSION}" style={{ display: "flex", flexDirection: "column", gap: 14 }}><div><div style={{ fontSize: 11, fontWeight: 600, color: "#64748b", letterSpacing: "0.04em", marginBottom: 6 }}>요약본</div><h4 style={{ margin: "0 0 8px", fontSize: 15, fontWeight: 700 }}>{sampleMeetingSummary.title}</h4><p style={{ margin: 0, fontSize: 13, lineHeight: 1.55, color: "#334155" }}>{sampleMeetingSummary.overview}</p></div><div><div style={{ fontSize: 12, fontWeight: 600, marginBottom: 6 }}>핵심 논의</div><ul style={{ margin: 0, paddingLeft: 18, fontSize: 13, lineHeight: 1.5 }}>{sampleMeetingSummary.keyPoints.map((point, i) => (<li key={i}>{point}</li>))}</ul></div><div><div style={{ fontSize: 12, fontWeight: 600, marginBottom: 6 }}>결정</div>{sampleDecisions.length ? (<ul style={{ margin: 0, paddingLeft: 18, fontSize: 13 }}>{sampleDecisions.map((d) => (<li key={d.id}>{d.text}</li>))}</ul>) : (<p style={{ margin: 0, fontSize: 12, color: "#94a3b8" }}>이번 회의에서 확정된 결정이 없습니다.</p>)}</div><div><div style={{ fontSize: 12, fontWeight: 600, marginBottom: 6 }}>할 일</div><ul style={{ margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 8 }}>{sampleActionItems.map((a) => (<li key={a.id} style={{ padding: "8px 10px", border: "1px solid #e2e8f0", borderRadius: 8, fontSize: 13 }}><div style={{ fontWeight: 600 }}>{a.task}</div><div style={{ fontSize: 11, color: "#64748b", marginTop: 4 }}>{[a.owner, a.dueDate].filter(Boolean).join(" · ")}</div></li>))}</ul></div></div>`;

export const PREVIEW_SAMPLE_DRAFT_TIMELINE_JSX = `<div className="jy-preview-draft-timeline" data-jy-preview-sample="${PREVIEW_SAMPLE_WIRING_VERSION}" style={{ display: "flex", flexDirection: "column", gap: 10 }}><div style={{ fontSize: 11, fontWeight: 600, color: "#64748b", letterSpacing: "0.04em" }}>초안 생성 타임라인</div><ol style={{ margin: 0, paddingLeft: 18, fontSize: 13, lineHeight: 1.5 }}>{sampleDraftTimeline.map((step) => (<li key={step.id} style={{ marginBottom: 8 }}><span style={{ fontWeight: 600 }}>{step.step}</span><span style={{ color: "#64748b" }}> — {step.description}</span></li>))}</ol></div>`;
