-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_CHUNK_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_CHUNK_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_CHUNK_DEACTIVATE';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_CHUNK_GENERATE';
