import type { AgentDefinition } from "@/lib/agents/agentDefinitionTypes";

export const DEFAULT_AGENTS: readonly AgentDefinition[] = [
  {
    id: "ai-planner",
    name: "AI기획자",
    type: "planner",
    description: "사용자 아이디어를 프로젝트 방향과 의사결정 항목으로 구조화한다.",
    runtimeMode: "llm",
    responsibilities: [
      "아이디어 구체화",
      "프로젝트 목적 정리",
      "필수 의사결정 항목 도출",
      "대화 기반 프로젝트 준비",
    ],
    defaultCapabilities: ["project.idea.structure", "orchestration.intent.route"],
    allowedConnectors: [],
    inputContract: { requiredContext: ["conversation", "projectContext"] },
    outputContract: { outputTypes: ["structuredIdea", "decisionItems", "summary"] },
    promptProfile: "ideation",
    governanceProfile: "requirements-orchestration",
    enabled: true,
  },
  {
    id: "ai-analyst",
    name: "AI분석가",
    type: "analyst",
    description: "서비스 액터, 흐름, 업무 규칙을 분석한다.",
    runtimeMode: "llm",
    responsibilities: ["액터 분석", "서비스 흐름 분석", "업무 규칙 정리"],
    defaultCapabilities: ["service.flow.analysis"],
    allowedConnectors: [],
    inputContract: { requiredContext: ["conversation", "structuredIdea"] },
    outputContract: { outputTypes: ["actorModel", "serviceFlow", "businessRules"] },
    promptProfile: "actor_flow",
    enabled: true,
  },
  {
    id: "ai-architect",
    name: "AI설계자",
    type: "architect",
    description: "기능 범위·체크리스트·화면/API 정의 단계를 설계한다.",
    runtimeMode: "llm",
    responsibilities: ["기능 범위 확정", "체크리스트 운영", "스테이지 전환 권고"],
    defaultCapabilities: ["feature.scope.design", "orchestration.intent.route"],
    allowedConnectors: [],
    inputContract: { requiredContext: ["serviceFlow", "featureDetailSlots"] },
    outputContract: { outputTypes: ["featureSpec", "screenOutline", "apiOutline"] },
    promptProfile: "feature_planning",
    governanceProfile: "stage-governance",
    enabled: true,
  },
  {
    id: "ai-designer",
    name: "AI디자이너",
    type: "designer",
    description: "UI·레이아웃·시각 톤과 프로토타입 UX를 제안한다.",
    runtimeMode: "llm",
    responsibilities: ["UI 방향 제안", "접근성·일관성", "프로토타입 시각 구조"],
    defaultCapabilities: ["uiux.prototype.design"],
    allowedConnectors: [],
    inputContract: { requiredContext: ["featureSpec", "prototypeContext"] },
    outputContract: { outputTypes: ["uiDirection", "layoutNotes"] },
    promptProfile: "designer",
    enabled: true,
  },
  {
    id: "ai-developer",
    name: "AI개발자",
    type: "developer",
    description: "구현 작업 지시를 생성하고 코드어시스턴트 실행과 연결된다.",
    runtimeMode: "code_assistant",
    responsibilities: ["구현 계획 수립", "Cursor 작업 지시 생성", "구현 결과 수집"],
    defaultCapabilities: ["cursor.implementation.plan"],
    allowedConnectors: ["cursor", "github"],
    inputContract: { requiredContext: ["featureSpec", "implementationPlan"] },
    outputContract: { outputTypes: ["cursorPrompt", "implementationResult", "commitSummary"] },
    promptProfile: "prototype_build",
    enabled: true,
  },
  {
    id: "ai-reviewer",
    name: "AI검수자",
    type: "reviewer",
    description: "구현 결과와 산출물을 검수한다.",
    runtimeMode: "llm",
    responsibilities: ["구현 결과 검수", "요구사항 반영 여부 확인", "개선사항 도출"],
    defaultCapabilities: ["source.review"],
    allowedConnectors: ["github"],
    inputContract: { requiredContext: ["implementationResult", "sourceDiff"] },
    outputContract: { outputTypes: ["reviewFindings", "approvalDecision"] },
    promptProfile: "prototype_review",
    enabled: true,
  },
  {
    id: "ai-security",
    name: "AI보안관",
    type: "security",
    description: "소스와 산출물의 보안 취약점을 점검한다.",
    runtimeMode: "llm",
    responsibilities: ["보안 취약점 점검", "보안 조치 항목 도출", "재점검 결과 판단"],
    defaultCapabilities: ["security.review"],
    allowedConnectors: ["github"],
    inputContract: { requiredContext: ["sourceDiff", "securityPolicy"] },
    outputContract: { outputTypes: ["securityFindings", "securityDecision"] },
    promptProfile: "security_reviewer",
    enabled: true,
  },
  {
    id: "ai-scm",
    name: "AI SCM",
    type: "scm",
    description: "PR·merge 흐름을 통제한다.",
    runtimeMode: "connector_worker",
    responsibilities: ["PR 상태 동기화", "merge 가능 여부", "브랜치 정책"],
    defaultCapabilities: ["git.pr.merge.control"],
    allowedConnectors: ["github"],
    inputContract: { requiredContext: ["pullRequest", "branchPolicy"] },
    outputContract: { outputTypes: ["mergeDecision", "prStatus"] },
    enabled: true,
  },
  {
    id: "ai-operator",
    name: "AI운영자",
    type: "operator",
    description: "메모·요약·우선순위 추천 등 운영 보조.",
    runtimeMode: "llm",
    responsibilities: ["메모 요약", "요청 분류", "우선순위 추천"],
    defaultCapabilities: [],
    allowedConnectors: [],
    inputContract: { requiredContext: ["memoContext"] },
    outputContract: { outputTypes: ["memoSummary", "priorityHint"] },
    promptProfile: "memo",
    enabled: true,
  },
] as const;
