import type { CapabilityDefinition } from "@/lib/agents/capabilityDefinitionTypes";

export const DEFAULT_CAPABILITIES: readonly CapabilityDefinition[] = [
  {
    id: "project.idea.structure",
    name: "아이디어 구조화",
    category: "planning",
    description: "사용자 대화를 기반으로 프로젝트 아이디어를 구조화한다.",
    allowedAgentTypes: ["planner"],
    governanceChecks: ["stage:ideation"],
    enabled: true,
  },
  {
    id: "service.flow.analysis",
    name: "서비스 흐름 분석",
    category: "analysis",
    description: "액터, 사용자 흐름, 서비스 흐름을 분석한다.",
    allowedAgentTypes: ["analyst"],
    governanceChecks: ["stage:service-flow"],
    enabled: true,
  },
  {
    id: "feature.scope.design",
    name: "기능 범위 설계",
    category: "architecture",
    description: "프로젝트 기능 범위와 구현 단위를 설계한다.",
    allowedAgentTypes: ["architect"],
    governanceChecks: ["stage:feature-detail"],
    enabled: true,
  },
  {
    id: "uiux.prototype.design",
    name: "UI/UX 프로토타입 설계",
    category: "design",
    description: "화면 구조와 사용자 경험 흐름을 설계한다.",
    allowedAgentTypes: ["designer"],
    enabled: true,
  },
  {
    id: "cursor.implementation.plan",
    name: "Cursor 구현 작업 지시 생성",
    category: "development",
    description: "Cursor가 수행할 수 있는 구현 단위 작업 지시를 생성한다.",
    allowedAgentTypes: ["developer"],
    requiredConnectors: ["cursor"],
    governanceChecks: ["connector:cursor"],
    enabled: true,
  },
  {
    id: "source.review",
    name: "소스 검수",
    category: "review",
    description: "AI개발자가 생성한 소스 변경사항을 검토한다.",
    allowedAgentTypes: ["reviewer"],
    requiredConnectors: ["github"],
    enabled: true,
  },
  {
    id: "security.review",
    name: "보안 점검",
    category: "security",
    description: "소스 및 산출물의 보안 취약점을 점검한다.",
    allowedAgentTypes: ["security"],
    requiredConnectors: ["github"],
    enabled: true,
  },
  {
    id: "git.pr.merge.control",
    name: "PR/Merge 통제",
    category: "scm",
    description: "GitHub PR 상태, 머지 가능 여부, 병합 흐름을 통제한다.",
    allowedAgentTypes: ["scm"],
    requiredConnectors: ["github"],
    enabled: true,
  },
  {
    id: "orchestration.intent.route",
    name: "의도 라우팅",
    category: "governance",
    description: "Requirements intent router + registry guard 경로.",
    allowedAgentTypes: ["planner", "architect", "developer"],
    governanceChecks: ["registry-guard"],
    enabled: true,
  },
  {
    id: "orchestration.timeline.record",
    name: "오케스트레이션 타임라인 기록",
    category: "timeline",
    description: "promptTimeline / orchestrationTraceGroup 기록.",
    enabled: true,
  },
  {
    id: "orchestration.projection.aggregate",
    name: "집계 프로젝션",
    category: "projection",
    description: "Governed aggregate + slim read model.",
    enabled: true,
  },
] as const;
