/**
 * Internal, stable codes for feature-generation entry outcomes (no HTTP mapping).
 */

export const FEATURE_GENERATION_ENTRY_CODE = {
  READY: "READY",
  NEEDS_CONFIRMATION: "NEEDS_CONFIRMATION",
  BLOCKED: "BLOCKED",
  BLOCKED_NO_REQUIREMENTS: "BLOCKED_NO_REQUIREMENTS",
  BLOCKED_VAGUE_INPUT: "BLOCKED_VAGUE_INPUT",
  BLOCKED_CONFLICT: "BLOCKED_CONFLICT",
  NEEDS_CONFIRMATION_AUTH: "NEEDS_CONFIRMATION_AUTH",
  NEEDS_CONFIRMATION_ACCESS_SCOPE: "NEEDS_CONFIRMATION_ACCESS_SCOPE",
  NEEDS_CONFIRMATION_GENERIC: "NEEDS_CONFIRMATION_GENERIC",
} as const;

export type FeatureGenerationEntryCode =
  (typeof FEATURE_GENERATION_ENTRY_CODE)[keyof typeof FEATURE_GENERATION_ENTRY_CODE];
