-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'SERVICE_VALIDATION_DOWNLOAD_TEST_SUCCEEDED';
ALTER TYPE "AuditAction" ADD VALUE 'SERVICE_VALIDATION_DOWNLOAD_TEST_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'SERVICE_VALIDATION_DOWNLOAD_TEST_RETRIED';
ALTER TYPE "AuditAction" ADD VALUE 'SERVICE_VALIDATION_LEGACY_SHARED_EVIDENCE_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_SERVICE_VALIDATION_HISTORY_VIEWED';
