export { DesktopShell } from "@/components/layout/DesktopShell";
export { MobileShell, type MobileShellProps } from "@/components/layout/MobileShell";
export { MobileTopBar, type MobileTopBarProps } from "@/components/layout/MobileTopBar";
export { ResponsivePageContainer, type ResponsivePageContainerProps } from "@/components/layout/ResponsivePageContainer";
export { ResponsiveShell, type ResponsiveShellProps } from "@/components/layout/ResponsiveShell";
export { WorkspaceModeProvider, useWorkspaceMode, useWorkspaceModeOptional } from "@/components/layout/WorkspaceModeContext";
export { WorkspaceModeSwitcher } from "@/components/layout/WorkspaceModeSwitcher";
export { PlatformMainFrame } from "@/components/layout/PlatformMainFrame";
export { TopRightToolbar, type TopRightToolbarMe, type TopRightToolbarProps } from "@/components/layout/TopRightToolbar";
export { LAYOUT_MOBILE_BREAKPOINT, useViewport } from "@/components/layout/useViewport";
