import type { KnowledgePack } from "@/lib/knowledge-packs/types";

const PACK_KAKAO_LOGIN: KnowledgePack = {
  id: "auth.kakao-login",
  name: "Kakao Login",
  version: "1.0.0",
  scope: "PLATFORM",
  category: "AUTH",
  agents: ["AI_DEVELOPER"],
  status: "ACTIVE",
  summary:
    "Kakao Login은 Kakao Developers 기반 OAuth 인증 연계 지식팩입니다. JYOrchestration에서는 카카오 로그인 버튼, 인가 요청, Redirect URI, 토큰 처리, 사용자 정보 조회, 로그아웃/연결 끊기 흐름을 프로토타입과 실제 구현 단계에서 구분해 설계하기 위한 기준으로 사용합니다.",
  license: {
    type: "EXTERNAL_SERVICE",
    notes: [
      "Kakao Developers 정책과 앱 설정, API 이용 약관 확인 필요",
      "동의항목·개인정보 처리방침·검수 요건은 서비스 유형에 따라 달라질 수 있다.",
    ],
  },
  recommendedUseCases: [
    "국내 사용자 대상 서비스에서 카카오 로그인이 필요한 경우",
    "소셜 로그인 기반 회원가입/로그인 UX가 필요한 경우",
    "카카오 사용자 정보 조회가 필요한 경우",
    "프로토타입에서 카카오 로그인 흐름을 실제 운영과 유사하게 표현해야 하는 경우",
    "OAuth 기반 인증 흐름을 AI개발자가 구현 지침으로 받아야 하는 경우",
  ],
  notRecommendedUseCases: [
    "Redirect URI, 앱 키, 동의항목 설정 없이 바로 실제 연동하려는 경우",
    "Client Secret이나 Access Token을 프론트엔드에 노출하려는 경우",
    "카카오 검수/권한 조건이 필요한 API를 승인 없이 사용하려는 경우",
    "단순 버튼 Mock만으로 실제 로그인 구현이 완료된 것처럼 보이게 하려는 경우",
    "개인정보 수집/저장 정책 없이 사용자 정보를 저장하려는 경우",
  ],
  capabilities: [
    "카카오 로그인 버튼 UX",
    "OAuth 인가 요청",
    "Redirect URI 기반 콜백 처리",
    "Access Token 처리",
    "사용자 정보 조회",
    "로그아웃",
    "연결 끊기",
    "인증 실패/취소/설정 오류 처리",
    "프로토타입용 Simulator/Mock 로그인 흐름",
    "보안 기준 기반 Secret 관리",
  ],
  constraints: [
    "Kakao Developers 앱 설정이 필요하다.",
    "Redirect URI 등록이 필요하다.",
    "REST API Key, JavaScript Key, Client Secret을 구분해야 한다.",
    "Client Secret과 Access Token은 서버 측에서 안전하게 처리해야 한다.",
    "사용자 정보 수집 항목은 동의항목 설정과 개인정보 처리방침에 맞아야 한다.",
    "일부 API는 권한/검수/앱 설정 조건이 필요할 수 있다.",
    "프로토타입에서는 실제 Kakao API 호출이 아니라 Simulator/Mock 흐름으로 대체할 수 있다.",
  ],
  implementationGuidelines: [
    "Kakao Login은 단순 로그인 버튼이 아니라 OAuth 인증 흐름으로 설계한다.",
    "프론트엔드는 로그인 시작 버튼과 인가 요청 진입을 담당한다.",
    "Redirect URI 콜백은 서버 또는 안전한 인증 처리 계층에서 처리한다.",
    "Access Token, Refresh Token, Client Secret은 프론트엔드에 노출하지 않는다.",
    "로그인 성공 후 사용자 정보 조회 흐름을 분리한다.",
    "로그아웃과 연결 끊기는 의미가 다르므로 별도 동작으로 구분한다.",
    "프로토타입에서는 `KakaoAuthModule`, `KakaoAuthAdapter`, `KakaoAuthSimulationConnector` 구조로 표현할 수 있다.",
    "외부 Kakao 호출부는 `SIMULATOR`, `SANDBOX`, `REAL` 모드로 분리 가능한 구조를 권장한다.",
    "인증 실패, 사용자 취소, Redirect URI 불일치, 앱 키 오류, 토큰 만료를 오류 시나리오에 포함한다.",
  ],
  cursorPromptRules: [
    "사용자가 Kakao Login을 요구하면 OAuth 인증 흐름으로 설계하도록 지시한다.",
    "단순 버튼 Mock만 만들지 말고 로그인 시작, 콜백 처리, 사용자 정보 조회, 실패/취소 상태를 포함한다.",
    "실제 Kakao API Key나 Secret을 코드에 하드코딩하지 않도록 지시한다.",
    "Secret은 서버 환경변수 또는 플랫폼 Secret 저장소를 사용하도록 지시한다.",
    "프로토타입 단계에서는 SimulationConnector를 사용하고 실제 API 호출은 범위 밖으로 분리한다.",
    "Redirect URI, 앱 키, 동의항목 설정 필요성을 주석/문서/환경설정 안내로 남긴다.",
    "인증 성공 후 내부 세션 생성 또는 사용자 상태 반영 흐름을 포함한다.",
  ],
  forbiddenPatterns: [
    "Client Secret을 프론트엔드 코드에 넣는 것 금지",
    "Access Token을 localStorage에 장기 저장하는 것 금지",
    "Kakao 앱 키를 운영 Secret처럼 하드코딩하는 것 금지",
    "Redirect URI 설정 없이 실제 연동된 것처럼 구현 금지",
    "사용자 동의 없이 개인정보 필드를 저장하는 코드 금지",
    "로그인 버튼만 만들고 인증 완료로 처리하는 단순 Mock 금지",
    "로그아웃과 연결 끊기를 동일 기능으로 처리 금지",
    "공식 문서 확인 없이 오류 코드나 API endpoint를 임의로 만드는 것 금지",
  ],
  reviewChecklist: [
    "OAuth 인가 요청 흐름이 표현되었는가",
    "Redirect URI/콜백 처리 구조가 분리되었는가",
    "Token/Secret이 프론트에 노출되지 않는가",
    "사용자 정보 조회 흐름이 로그인 성공 이후로 분리되었는가",
    "실패/취소/토큰 만료/설정 오류 시나리오가 있는가",
    "프로토타입이 실제 API 호출인지 Simulator인지 명확한가",
    "로그아웃과 연결 끊기가 구분되었는가",
    "개인정보 수집/저장 주의사항이 반영되었는가",
    "Cursor 프롬프트에 보안 금지사항이 포함되는가",
  ],
  alternatives: [
    "자체 로그인",
    "OAuth 2.0 범용 인증",
    "네이버 로그인",
    "Google Login",
    "금융인증서",
    "공동인증서",
    "사내 SSO",
  ],
  references: [
    { label: "Kakao Developers", url: "https://developers.kakao.com/" },
    { label: "Kakao Login 문서", url: "https://developers.kakao.com/docs/latest/ko/kakaologin/common" },
    { label: "Kakao REST API", url: "https://developers.kakao.com/docs/latest/ko/rest-api/README" },
  ],
};

/** 플랫폼 정적 seed — Auth 지식팩만 (Grid는 `developerGridPacks.ts`). */
export const DEVELOPER_AUTH_KNOWLEDGE_PACKS: readonly KnowledgePack[] = [PACK_KAKAO_LOGIN];
